### ISSUE TITLE
Robot Install Software Commands

### ISSUE THREAD

**Issue by ncharlton02** [InspireRobotics/sumobots-old#134]
git clone --branch v2 https://github.com/metachris/RPIO
cd RPIO
sudo apt-get install python-dev python3-dev
sudo python3 setup.py install
cd ..
git clone https://github.com/InspireRobotics/sumobots

**Comment by ncharlton02** [comment]
**Orange Robot**
- [x] Install Software
- [x] Fix Robot Code (uncomment)  
- [x] Run on boot
- [x] Code Robot
- [x] Test Everything

**Green Robot**
- [x] Install Software
- [x] Fix Robot Code (uncomment)  
- [x] Run on boot
- [x] Code Robot
- [x] Test Everything

**Blue Robot**
- [x] Install Software
- [x] Fix Robot Code (uncomment)  
- [x] Run on boot
- [x] Update Robot Code
- [x] Test Everything

**Purple Robot/Backup**
- [x] Install Software
- [x] Fix Robot Code (uncomment)  
- [x] Run on boot
- [x] Update Robot Code
- [x] Test Everything

**Comment by ncharlton02** [comment]
Auto boot command: 
@sudo lxterminal -e sudo python3 /home/pi/Desktop/robot/networking.py

File: ./home/pi/.config/lxsession/LXDE-pi/autostart

**Comment by DevOrc** [comment]
@sudo lxterminal -e sudo python3 /home/pi/Desktop/robot/networking.py
